yarnPath: .yarn/releases/yarn-remote.cjs

packageExtensions:
  '@nextui-org/avatar@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/badge@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/button@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/card@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/chip@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/checkbox@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/code@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/link@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/pagination@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/radio@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/spinner@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/switch@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/user@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/progress@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/input@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/image@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/table@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/spacer@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/divider@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/kbd@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/skeleton@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/scroll-shadow@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/listbox@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/menu@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/dropdown@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/modal@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/navbar@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/popover@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/system@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/tooltip@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/use-aria-modal-overlay@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/use-aria-multiselect@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/accordion@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/aria-utils@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/framer-transitions@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/react@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/ripple@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/select@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/snippet@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/tabs@*':
    peerDependencies:
      react-dom: '*'
